In [60]:
import pandas as pd

In [61]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=["A","B","C"],index=["X","Y","Z"])

In [62]:
df.head(3)

   A  B  C
X  1  2  3
Y  4  5  6
Z  7  8  9

In [63]:
df.head(2)

   A  B  C
X  1  2  3
Y  4  5  6

In [64]:
df.tail(2)

   A  B  C
Y  4  5  6
Z  7  8  9

In [65]:
df.index

Index(['X', 'Y', 'Z'], dtype='str')

In [66]:
df.columns

Index(['A', 'B', 'C'], dtype='str')

In [67]:
df.index.tolist()

['X', 'Y', 'Z']

In [68]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, X to Z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 99.0 bytes

In [69]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [70]:
df.nunique()

A    3
B    3
C    3
dtype: int64

In [71]:
df["A"].unique()

array([1, 4, 7])

In [72]:
df.shape

(3, 3)

In [73]:
df.size

9

In [74]:
coffee = pd.read_csv('/Users/adityasaraswat/Downloads/Aditya/Codes/machine-learning/complete-pandas-tutorial-master/warmup-data/coffee.csv')

In [75]:
coffee.head(5)

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [76]:
results = pd.read_parquet('/Users/adityasaraswat/Downloads/Aditya/Codes/machine-learning/complete-pandas-tutorial-master/data/results.parquet')

In [77]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [78]:
olympics = pd.read_excel('/Users/adityasaraswat/Downloads/Aditya/Codes/machine-learning/complete-pandas-tutorial-master/data/olympics-data.xlsx')

KeyboardInterrupt:

In [ ]:
olympics.head(5)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [ ]:
bios = pd.read_csv('/Users/adityasaraswat/Downloads/Aditya/Codes/machine-learning/complete-pandas-tutorial-master/data/bios.csv')

In [ ]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [ ]:
coffee.sample(10)

          Day Coffee Type  Units Sold
10   Saturday    Espresso          45
4   Wednesday    Espresso          35
1      Monday       Latte          15
11   Saturday       Latte          35
3     Tuesday       Latte          20
6    Thursday    Espresso          40
0      Monday    Espresso          25
8      Friday    Espresso          45
9      Friday       Latte          35
13     Sunday       Latte          35

In [ ]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [ ]:
coffee.loc[[0,3,5],["Day","Units Sold"]]

         Day  Units Sold
0     Monday          25
3    Tuesday          20
5  Wednesday          25

In [ ]:
coffee.iloc[[4,8,12],[0,2]]

          Day  Units Sold
4   Wednesday          35
8      Friday          45
12     Sunday          45

In [ ]:
coffee.iloc[3:7,[2]] = 200

In [ ]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte         200
4   Wednesday    Espresso         200
5   Wednesday       Latte         200
6    Thursday    Espresso         200
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [ ]:
coffee = pd.read_csv('/Users/adityasaraswat/Downloads/Aditya/Codes/machine-learning/complete-pandas-tutorial-master/warmup-data/coffee.csv')

In [ ]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [ ]:
print(coffee.at[0,"Units Sold"])

25

In [ ]:
print(coffee.iat[0,2])

25

In [ ]:
coffee.Day

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: str

In [ ]:
coffee["Units Sold"]

0     25
1     15
2     30
3     20
4     35
5     25
6     40
7     30
8     45
9     35
10    45
11    35
12    45
13    35
Name: Units Sold, dtype: int64

In [ ]:
coffee.sort_values(["Units Sold","Coffee Type"],ascending=[1,0])

          Day Coffee Type  Units Sold
1      Monday       Latte          15
3     Tuesday       Latte          20
5   Wednesday       Latte          25
0      Monday    Espresso          25
7    Thursday       Latte          30
2     Tuesday    Espresso          30
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
4   Wednesday    Espresso          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

In [ ]:
for index, rows in coffee.iterrows():
    print(index)
    print(rows)
    print("\n\n\n")

0
Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object




1
Day            Monday
Coffee Type     Latte
Units Sold         15
Name: 1, dtype: object




2
Day             Tuesday
Coffee Type    Espresso
Units Sold           30
Name: 2, dtype: object




3
Day            Tuesday
Coffee Type      Latte
Units Sold          20
Name: 3, dtype: object




4
Day            Wednesday
Coffee Type     Espresso
Units Sold            35
Name: 4, dtype: object




5
Day            Wednesday
Coffee Type        Latte
Units Sold            25
Name: 5, dtype: object




6
Day            Thursday
Coffee Type    Espresso
Units Sold           40
Name: 6, dtype: object




7
Day            Thursday
Coffee Type       Latte
Units Sold           30
Name: 7, dtype: object




8
Day              Friday
Coffee Type    Espresso
Units Sold           45
Name: 8, dtype: object




9
Day            Friday
Coffee Type     Latte
Units Sold         35
Name: 9, dtype: object




10
Day            Saturday
Coffee Type    Espresso
Units Sold           45
Name: 10, dtype: object




11
Day            Saturday
Coffee Type       Latte
Units Sold           35
Name: 11, dtype: object




12
Day              Sunday
Coffee Type    Espresso
Units Sold           45
Name: 12, dtype: object




13
Day            Sunday
Coffee Type     Latte
Units Sold         35
Name: 13, dtype: object

In [ ]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [ ]:
bios.loc[bios['height_cm']>215,['name','height_cm']]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [ ]:
bios[(bios['height_cm']>215)&(bios['born_country']=='USA')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [ ]:
bios[bios['name'].str.contains("keith",case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN
117676,119195,Duncan Keith,1983-07-16,Winnipeg,Manitoba,CAN,Canada,185.0,88.0,NaN
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN
127310,129749,Tracy Keith-Matchitt,1990-03-30,Palmerston North,Manawatu-Wanganui,NZL,Cook Islands,167.0,60.0,NaN

In [ ]:
bios[bios['born_country'].isin(["USA","FRA","GBR"]) & (bios['name'].str.startswith("Keith"))]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
14577,14674,Keith Harrison,1933-03-28,Birmingham,England,GBR,Great Britain,NaN,NaN,NaN
16166,16281,Keith Reynolds,1963-12-25,Solihull,England,GBR,Great Britain,173.0,68.0,NaN
18734,18862,Keith Sinclair,1945-06-26,Sunderland,England,GBR,Great Britain,190.0,79.0,NaN
29897,30123,Keith Langley,1961-06-03,Aldershot,England,GBR,Great Britain,173.0,70.0,NaN
34011,34275,Keith Remfry,1947-11-17,Ealing,England,GBR,Great Britain,193.0,114.0,2015-09-16
46885,47234,Keith Collin,1937-01-18,Marylebone,England,GBR,Great Britain,168.0,63.0,1991-03-06
50929,51288,Keith Carter,1924-08-30,Akron,Ohio,USA,United States,NaN,NaN,2013-05-03
51185,51544,Keith Russell,1948-01-15,Mesa,Arizona,USA,United States,188.0,73.0,NaN
52913,53288,Keith Erickson,1944-04-19,San Francisco,California,USA,United States,196.0,86.0,NaN
55317,55712,Keith Boxell,1958-05-06,Clapham,England,GBR,Great Britain,170.0,87.0,NaN
57818,58226,Keith Peache,1947-08-10,Lewisham,England,GBR,Great Britain,180.0,98.0,NaN
61748,62202,Keith Grogono,1912-11-04,Stratford,England,GBR,Great Britain,NaN,NaN,1999-03-22
62620,63086,Keith Musto,1936-01-12,Rochford,England,GBR,Great Britain,174.0,72.0,NaN
62678,63144,Keith Notary,1960-01-22,Merritt Island,Florida,USA,United States,170.0,66.0,NaN
68324,68841,Keith Angus,1943-04-05,Sheffield,England,GBR,Great Britain,170.0,59.0,NaN
68472,68989,Keith Cullen,1972-06-13,Ilford,England,GBR,Great Britain,177.0,61.0,NaN
68997,69514,Keith Stock,1957-03-18,Woolwich,England,GBR,Great Britain,176.0,73.0,NaN
77550,78141,Keith Brantly,1962-05-23,Scott Air Force Base,Illinois,USA,United States,180.0,64.0,NaN
84097,84766,Keith Christiansen,1944-07-14,International Falls,Minnesota,USA,United States,165.0,69.0,2018-11-05
94646,95413,Keith Meyer,1938-06-20,Geneva,Illinois,USA,United States,NaN,NaN,2010-07-25
95267,96037,Keith Oliver,1947-10-27,Liverpool,England,GBR,Great Britain,172.0,68.0,NaN
96452,97229,Keith Schellenberg,1929-03-13,Middlesbrough,England,GBR,Great Britain,NaN,NaN,2019-10-28
97499,98286,Keith Tkachuk,1972-03-28,Melrose,Massachusetts,USA,United States,188.0,102.0,NaN
98068,98860,Keith Wegeman,1929-08-28,Denver,Colorado,USA,United States,NaN,NaN,1974-08-22
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN

In [ ]:
bios[bios['born_region'].str.contains("Uttar Pradesh")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
270,271,Nora Polley,1894-07-29,Budaun,Uttar Pradesh,IND,India,NaN,NaN,1988-01-01
17391,17511,Kevin Carton,1933-10-26,Lucknow,Uttar Pradesh,IND,Australia,174.0,64.0,2017-08-03
19015,19148,Dhyan Chand,1905-08-28,Allahabad,Uttar Pradesh,IND,India,169.0,NaN,1979-12-03
19067,19201,Ashok Kumar,1950-06-01,Jhansi,Uttar Pradesh,IND,India,170.0,57.0,NaN
19083,19217,Muhammad Shahid,1960-04-14,Varanasi,Uttar Pradesh,IND,India,160.0,66.0,2016-07-20
19097,19231,Eric Pinniger,1902-12-28,Saharanpur,Uttar Pradesh,IND,India,180.0,NaN,1996-12-30
19112,19246,Frederick Seaman,1906-01-02,Allahabad,Uttar Pradesh,IND,India,NaN,NaN,2000-09-21
19142,19277,Jagbir Singh,1965-02-20,Agra,Uttar Pradesh,IND,India,180.0,71.0,NaN
19148,19283,Kunwar Digvijay Singh,1922-02-22,Barabanki,Uttar Pradesh,IND,India,NaN,NaN,1978-03-27
19150,19285,Mohinder Pal Singh,1962-10-16,Meerut,Uttar Pradesh,IND,India,178.0,78.0,NaN
19159,19294,Ravinder Pal Singh,1960-09-06,Sitapur,Uttar Pradesh,IND,India,168.0,63.0,2021-05-08
19167,19302,Vivek Singh,1967-08-01,Varanasi,Uttar Pradesh,IND,India,176.0,59.0,2007-02-02
19171,19306,Hardayal Singh,1928-11-28,Lucknow,Uttar Pradesh,IND,India,NaN,NaN,2018-08-17
19769,19908,Tony Hayde,1932-12-05,Dehradun,Uttar Pradesh,IND,New Zealand,NaN,NaN,2014-11-20
19870,20010,Khurshid Aslam,1936-04-06,Lucknow,Uttar Pradesh,IND,Pakistan,179.0,70.0,1993-01-01
25075,25265,John Nicholas,1879-07-24,Allahabad,Uttar Pradesh,IND,Great Britain,NaN,NaN,1929-09-29
25633,25825,Bahadur Chettri Ram,1937-02-15,Dehradun,Uttar Pradesh,IND,India,157.0,59.0,2000-12-04
34505,34774,Edward Clarke,1888-10-01,Lucknow,Uttar Pradesh,IND,Great Britain,NaN,NaN,1982-05-16
42524,42847,Jaspal Rana,1976-06-28,Uttarkashi,Uttar Pradesh,IND,India,175.0,85.0,NaN
53843,54229,Sachin Nag,1920-07-05,Varanasi,Uttar Pradesh,IND,India,NaN,NaN,1987-08-19
58311,58725,Bishambar Singh,1940-10-10,Bahipur,Uttar Pradesh,IND,India,156.0,57.0,2004-01-01
70877,71409,Henry Rebello,1928-11-17,Lucknow,Uttar Pradesh,IND,India,NaN,NaN,2013-08-27
70905,71437,Vijay Singh Chauhan,1949-01-21,Jaitpur Kalan,Uttar Pradesh,IND,India,183.0,78.0,NaN
73842,74411,Mazhar-Ul-Haque Khan,1923-02-23,Bareilly,Uttar Pradesh,IND,Pakistan,NaN,NaN,1997-02-15
92335,93075,Abhinav Bindra,1982-09-28,Dehradun,Uttar Pradesh,IND,India,173.0,70.0,NaN
101942,102874,Satyadev Prasad,1979-09-19,Uttar Pradesh,Uttar Pradesh,IND,India,170.0,64.0,NaN
104825,105851,Abhinn Shyam Gupta,1979-10-22,Allahabad,Uttar Pradesh,IND,India,172.0,68.0,NaN
105134,106168,Akhil Kumar,1981-03-27,Faizabad,Uttar Pradesh,IND,India,165.0,54.0,NaN
107860,108998,Devesh Chauhan,1981-12-11,Etawah,Uttar Pradesh,IND,India,153.0,84.0,NaN
118989,120768,Danish Mujtaba,1988-12-20,Allahabad,Uttar Pradesh,IND,India,168.0,66.0,NaN
119073,120855,Tushar Khandker,1985-04-05,Jhansi,Uttar Pradesh,IND,India,171.0,NaN,NaN
119209,121003,Annu Raj Singh,1984-02-17,Aligarh,Uttar Pradesh,IND,India,164.0,53.0,NaN
119637,121463,Ram Singh Yadav,1980-11-07,Varanassi,Uttar Pradesh,IND,India,NaN,NaN,NaN
119638,121464,Sudha Singh,1986-06-25,Raebareli,Uttar Pradesh,IND,India,158.0,45.0,NaN
121367,123352,Narsingh Yadav,1989-08-06,Varanasi,Uttar Pradesh,IND,India,167.0,74.0,NaN
121382,123367,Garima Chaudhary,1990-04-02,Meerut,Uttar Pradesh,IND,India,168.0,63.0,NaN
128055,130560,Navjot Kaur,1995-03-07,Muzaffarnagar,Uttar Pradesh,IND,India,167.0,53.0,NaN
128064,130570,Vandana Katariya,1992-04-15,Lucknow,Uttar Pradesh,IND,India,159.0,48.0,NaN
131607,134417,Ankit Sharma,1992-07-20,Pinahat,Uttar Pradesh,IND,India,177.0,75.0,NaN
131619,134433,Manu Attri,1992-12-31,Meerut,Uttar Pradesh,IND,India,172.0,73.0,NaN
131637,134453,Mairaj Ahmad Khan,1975-11-02,Khurja,Uttar Pradesh,IND,India,181.0,82.0,NaN
140263,143766,Satish Kumar,1989-05-04,Bulandshahr,Uttar Pradesh,IND,India,188.0,NaN,NaN

In [ ]:
bios.query('born_country == "USA" and born_city == "Seattle"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
11030,11088,David Halpern,1955-08-18,Seattle,Washington,USA,United States,178.0,79.0,NaN
12800,12870,Todd Trewin,1958-04-20,Seattle,Washington,USA,United States,180.0,75.0,NaN
15476,15583,Scott McKinley,1968-10-15,Seattle,Washington,USA,United States,183.0,75.0,NaN
29079,29293,Joyce Tanac,1950-09-27,Seattle,Washington,USA,United States,156.0,49.0,NaN
31135,31371,Bill Kuhlemeier,1908-01-14,Seattle,Washington,USA,United States,NaN,NaN,2001-07-08
...,...,...,...,...,...,...,...,...,...,...
133392,136331,Hans Struzyna,1989-03-31,Seattle,Washington,USA,United States,188.0,91.0,NaN
135448,138662,Maude Davis Crossland,2003-03-19,Seattle,Washington,USA,Colombia,NaN,NaN,NaN
136993,140229,Jenell Berhorst,2003-12-13,Seattle,Washington,USA,United States,NaN,NaN,NaN
143507,147159,Nevin Harrison,2002-06-02,Seattle,Washington,USA,United States,175.0,73.0,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN

In [ ]:
coffee['price'] = 4.99
coffee

          Day Coffee Type  Units Sold  price
0      Monday    Espresso          25   4.99
1      Monday       Latte          15   4.99
2     Tuesday    Espresso          30   4.99
3     Tuesday       Latte          20   4.99
4   Wednesday    Espresso          35   4.99
5   Wednesday       Latte          25   4.99
6    Thursday    Espresso          40   4.99
7    Thursday       Latte          30   4.99
8      Friday    Espresso          45   4.99
9      Friday       Latte          35   4.99
10   Saturday    Espresso          45   4.99
11   Saturday       Latte          35   4.99
12     Sunday    Espresso          45   4.99
13     Sunday       Latte          35   4.99

In [ ]:
import numpy as np
coffee_new = coffee.copy()
coffee['new price'] = np.where(coffee['Coffee Type']== 'Espresso',3.99,5.99)
coffee

          Day Coffee Type  Units Sold  new price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [ ]:
coffee.drop(0)

          Day Coffee Type  Units Sold  price
1      Monday       Latte          15   4.99
2     Tuesday    Espresso          30   4.99
3     Tuesday       Latte          20   4.99
4   Wednesday    Espresso          35   4.99
5   Wednesday       Latte          25   4.99
6    Thursday    Espresso          40   4.99
7    Thursday       Latte          30   4.99
8      Friday    Espresso          45   4.99
9      Friday       Latte          35   4.99
10   Saturday    Espresso          45   4.99
11   Saturday       Latte          35   4.99
12     Sunday    Espresso          45   4.99
13     Sunday       Latte          35   4.99

In [ ]:
coffee_new.drop(columns=['price'],inplace=True)

In [ ]:
coffee_new

          Day Coffee Type  Units Sold  new price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [ ]:
coffee['revenue'] = coffee['Units Sold'] * coffee['new price']

In [ ]:
print(coffee_new.columns.tolist())

['Day', 'Coffee Type', 'Units Sold', 'new price', 'revenue']

In [ ]:
coffee

          Day Coffee Type  Units Sold  new price  revenue
0      Monday    Espresso          25       3.99    99.75
1      Monday       Latte          15       5.99    89.85
2     Tuesday    Espresso          30       3.99   119.70
3     Tuesday       Latte          20       5.99   119.80
4   Wednesday    Espresso          35       3.99   139.65
5   Wednesday       Latte          25       5.99   149.75
6    Thursday    Espresso          40       3.99   159.60
7    Thursday       Latte          30       5.99   179.70
8      Friday    Espresso          45       3.99   179.55
9      Friday       Latte          35       5.99   209.65
10   Saturday    Espresso          45       3.99   179.55
11   Saturday       Latte          35       5.99   209.65
12     Sunday    Espresso          45       3.99   179.55
13     Sunday       Latte          35       5.99   209.65

In [ ]:
coffee.rename(columns={'new price':'price'},inplace=True)

In [ ]:
coffee_new

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso          25   3.99    99.75
1      Monday       Latte          15   5.99    89.85
2     Tuesday    Espresso          30   3.99   119.70
3     Tuesday       Latte          20   5.99   119.80
4   Wednesday    Espresso          35   3.99   139.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   3.99   159.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   3.99   179.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   3.99   179.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   3.99   179.55
13     Sunday       Latte          35   5.99   209.65

In [ ]:
bios_new = bios.copy()

In [ ]:
bios_new['first_name'] = bios_new['name'].str.split(' ').str[0]

In [ ]:
bios_new.query('first_name == "Keith"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN,Keith
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31,Keith
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN,Keith
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09,Keith
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22,Keith
...,...,...,...,...,...,...,...,...,...,...,...
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN,Keith
102227,103168,Keith Beavers,1983-02-09,London,Ontario,CAN,Canada,185.0,75.0,NaN,Keith
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15,Keith
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN,Keith
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN,Keith

In [ ]:
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'])

In [ ]:
bios_new['born_year'] = bios_new['born_datetime'].dt.year
bios_new[['name','born_year']]

                         name  born_year
0       Jean-François Blanchy     1886.0
1              Arnaud Boetsch     1969.0
2                Jean Borotra     1898.0
3             Jacques Brugnon     1895.0
4                Albert Canet     1878.0
...                       ...        ...
145495      Polina Luchnikova     2002.0
145496    Valeriya Merkusheva     1999.0
145497        Yuliya Smirnova     1998.0
145498         André Foussard     1899.0
145499          Bill Phillips     1913.0

[145500 rows x 2 columns]

In [ ]:
bios_new.to_csv('/Users/adityasaraswat/Downloads/Aditya/Codes/machine-learning/complete-pandas-tutorial-master/data/bios_new.csv',index=False)

In [ ]:
bios_new['height category']= bios_new['height_cm'].apply(lambda x:'Short'if x<165 else('Average' if x<185 else 'Tall'))
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina,2002-01-30,2002.0,Average
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya,1999-09-20,1999.0,Average
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,1998-05-08,1998.0,Short
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André,1899-05-19,1899.0,Average
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,1913-07-15,1913.0,Tall

In [ ]:
def athelete_category(row):
    if row['height_cm'] < 175 and row['weight_kg'] < 70:
        return 'Lightweight'
    elif row['height_cm'] < 185 and row['weight_kg'] < 80:
        return 'Middleweight'
    else:
        return 'Heavyweight'
    
bios['Category'] = bios_new.apply(athelete_category,axis=1)

In [ ]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Heavyweight

In [ ]:
nocs = pd.read_csv('/Users/adityasaraswat/Downloads/Aditya/Codes/machine-learning/complete-pandas-tutorial-master/data/noc_regions.csv')

In [ ]:
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [ ]:
bios_new = pd.merge(bios,nocs,left_on='born_country',right_on='NOC',how='left')

In [ ]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,Category,NOC_y,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Heavyweight,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Middleweight,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Middleweight,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Lightweight,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Heavyweight,GBR,UK,NaN

In [ ]:
bios_new.rename(columns={'region':'born_country_full'},inplace=True)

In [ ]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,Category,NOC_y,born_country_full,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Heavyweight,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Middleweight,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Middleweight,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Lightweight,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Heavyweight,GBR,UK,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Lightweight,RUS,Russia,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Lightweight,RUS,Russia,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Lightweight,RUS,Russia,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,Heavyweight,FRA,France,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Heavyweight,AUS,Australia,NaN

In [ ]:
bios_new[bios_new['born_country_full']!=bios_new['NOC_x']][['name','born_country_full','NOC_x']]

                       name born_country_full    NOC_x
4              Albert Canet                UK   France
12                J. Defert               NaN   France
13           Étienne Durand               NaN   France
16               Guy Forget           Morocco   France
27       Guy, Baron Lejeune               NaN   France
...                     ...               ...      ...
145491        Matthew Wepke               NaN  Jamaica
145493   Landysh Falyakhova            Russia      ROC
145495    Polina Luchnikova            Russia      ROC
145496  Valeriya Merkusheva            Russia      ROC
145497      Yuliya Smirnova            Russia      ROC

[73210 rows x 3 columns]

In [ ]:
usa = bios[bios['born_country']=='USA'].copy()
gbr = bios[bios['born_country']=='GBR'].copy()
new_df = pd.concat([usa,gbr])
new_df.tail()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,Category
144811,148512,Benjamin Alexander,1983-05-08,London,England,GBR,Jamaica,NaN,NaN,NaN,Heavyweight
144815,148517,Ashley Watson,1993-10-28,Peterborough,England,GBR,Jamaica,NaN,NaN,NaN,Heavyweight
145005,148716,Peder Kongshaug,2001-08-13,Wimbledon,England,GBR,Norway,184.0,86.0,NaN,Heavyweight
145319,149041,Axel Brown,1992-04-02,Harrogate,England,GBR,Trinidad and Tobago,NaN,NaN,NaN,Heavyweight
145388,149111,Jean-Luc Baker,1993-10-07,Burnley,England,GBR,United States,NaN,NaN,NaN,Heavyweight

In [ ]:
combined_df = pd.merge(results,bios,on='athlete_id',how='left')
combined_df.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,...,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,Category
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Heavyweight
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Heavyweight
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Heavyweight
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Heavyweight
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Heavyweight

In [ ]:
coffee.loc[[2,3],'Units Sold'] = np.nan
coffee

          Day Coffee Type  Units Sold  price
0      Monday    Espresso        25.0   4.99
1      Monday       Latte        15.0   4.99
2     Tuesday    Espresso         NaN   4.99
3     Tuesday       Latte         NaN   4.99
4   Wednesday    Espresso        35.0   4.99
5   Wednesday       Latte        25.0   4.99
6    Thursday    Espresso        40.0   4.99
7    Thursday       Latte        30.0   4.99
8      Friday    Espresso        45.0   4.99
9      Friday       Latte        35.0   4.99
10   Saturday    Espresso        45.0   4.99
11   Saturday       Latte        35.0   4.99
12     Sunday    Espresso        45.0   4.99
13     Sunday       Latte        35.0   4.99

In [ ]:
coffee.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          14 non-null     str
 1   Coffee Type  14 non-null     str
 2   Units Sold   12 non-null     float64
 3   price        14 non-null     float64
dtypes: float64(2), str(2)
memory usage: 771.0 bytes

In [ ]:
coffee.isna().sum()

Day            0
Coffee Type    0
Units Sold     2
price          0
dtype: int64

In [ ]:
coffee = coffee.fillna(coffee['Units Sold'].mean())
coffee

          Day Coffee Type  Units Sold  price
0      Monday    Espresso   25.000000   4.99
1      Monday       Latte   15.000000   4.99
2     Tuesday    Espresso   34.166667   4.99
3     Tuesday       Latte   34.166667   4.99
4   Wednesday    Espresso   35.000000   4.99
5   Wednesday       Latte   25.000000   4.99
6    Thursday    Espresso   40.000000   4.99
7    Thursday       Latte   30.000000   4.99
8      Friday    Espresso   45.000000   4.99
9      Friday       Latte   35.000000   4.99
10   Saturday    Espresso   45.000000   4.99
11   Saturday       Latte   35.000000   4.99
12     Sunday    Espresso   45.000000   4.99
13     Sunday       Latte   35.000000   4.99

In [ ]:
coffee['Units Sold'].interpolate()

0     25.000000
1     15.000000
2     34.166667
3     34.166667
4     35.000000
5     25.000000
6     40.000000
7     30.000000
8     45.000000
9     35.000000
10    45.000000
11    35.000000
12    45.000000
13    35.000000
Name: Units Sold, dtype: float64

In [ ]:
coffee['Units Sold'] = coffee['Units Sold'].interpolate()
coffee

          Day Coffee Type  Units Sold  price
0      Monday    Espresso   25.000000   4.99
1      Monday       Latte   15.000000   4.99
2     Tuesday    Espresso   34.166667   4.99
3     Tuesday       Latte   34.166667   4.99
4   Wednesday    Espresso   35.000000   4.99
5   Wednesday       Latte   25.000000   4.99
6    Thursday    Espresso   40.000000   4.99
7    Thursday       Latte   30.000000   4.99
8      Friday    Espresso   45.000000   4.99
9      Friday       Latte   35.000000   4.99
10   Saturday    Espresso   45.000000   4.99
11   Saturday       Latte   35.000000   4.99
12     Sunday    Espresso   45.000000   4.99
13     Sunday       Latte   35.000000   4.99

In [ ]:
coffee.loc[[2,3],'Units Sold'] = np.nan
coffee

          Day Coffee Type  Units Sold  price
0      Monday    Espresso        25.0   4.99
1      Monday       Latte        15.0   4.99
2     Tuesday    Espresso         NaN   4.99
3     Tuesday       Latte         NaN   4.99
4   Wednesday    Espresso        35.0   4.99
5   Wednesday       Latte        25.0   4.99
6    Thursday    Espresso        40.0   4.99
7    Thursday       Latte        30.0   4.99
8      Friday    Espresso        45.0   4.99
9      Friday       Latte        35.0   4.99
10   Saturday    Espresso        45.0   4.99
11   Saturday       Latte        35.0   4.99
12     Sunday    Espresso        45.0   4.99
13     Sunday       Latte        35.0   4.99

In [ ]:
coffee.loc[[2,3],'Units Sold'] = np.nan

In [ ]:
coffee.dropna()
coffee.dropna(subset=['Units Sold'],inplace=True)

In [ ]:
coffee[coffee['Units Sold'].isna()]

       Day Coffee Type  Units Sold  price
2  Tuesday    Espresso         NaN   4.99
3  Tuesday       Latte         NaN   4.99

In [ ]:
coffee[coffee['Units Sold'].notna()]

          Day Coffee Type  Units Sold  price
0      Monday    Espresso        25.0   4.99
1      Monday       Latte        15.0   4.99
4   Wednesday    Espresso        35.0   4.99
5   Wednesday       Latte        25.0   4.99
6    Thursday    Espresso        40.0   4.99
7    Thursday       Latte        30.0   4.99
8      Friday    Espresso        45.0   4.99
9      Friday       Latte        35.0   4.99
10   Saturday    Espresso        45.0   4.99
11   Saturday       Latte        35.0   4.99
12     Sunday    Espresso        45.0   4.99
13     Sunday       Latte        35.0   4.99

In [ ]:
bios[bios['born_country']=='USA']['born_region'].value_counts()

born_region
California              1634
New York                 990
Illinois                 585
Pennsylvania             530
Massachusetts            530
New Jersey               381
Texas                    368
Minnesota                365
Ohio                     328
Michigan                 319
Washington               240
Florida                  235
Wisconsin                209
Colorado                 207
Connecticut              156
Indiana                  150
Oregon                   132
Georgia                  129
Virginia                 121
Maryland                 117
District of Columbia     107
Iowa                     102
Hawaiʻi                   95
Kansas                    94
Oklahoma                  93
Louisiana                 92
Utah                      91
Missouri                  91
North Carolina            86
Arizona                   83
New Hampshire             83
Vermont                   68
Mississippi               66
Alabama                   64
Tennessee                 62
Kentucky                  62
Nebraska                  60
Rhode Island              56
Montana                   55
Maine                     50
South Carolina            50
Alaska                    45
Arkansas                  42
Idaho                     41
New Mexico                38
Nevada                    36
South Dakota              27
West Virginia             24
Delaware                  22
North Dakota              16
Wyoming                   14
Name: count, dtype: int64

In [ ]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso          25   3.99    99.75
1     Monday       Latte          15   5.99    89.85
2    Tuesday    Espresso          30   3.99   119.70
3    Tuesday       Latte          20   5.99   119.80
4  Wednesday    Espresso          35   3.99   139.65

In [ ]:
coffee.groupby(['Coffee Type'])['Units Sold'].sum()

Coffee Type
Espresso    265
Latte       195
Name: Units Sold, dtype: int64

In [ ]:
coffee.groupby(['Coffee Type'])['Units Sold'].mean()

Coffee Type
Espresso    37.857143
Latte       27.857143
Name: Units Sold, dtype: float64

In [ ]:
coffee.groupby(['Coffee Type']).agg({'Units Sold':'sum','price':'mean'})

             Units Sold  price
Coffee Type
Espresso            265   3.99
Latte               195   5.99

In [ ]:
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso          25   3.99    99.75
1      Monday       Latte          15   5.99    89.85
2     Tuesday    Espresso          30   3.99   119.70
3     Tuesday       Latte          20   5.99   119.80
4   Wednesday    Espresso          35   3.99   139.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   3.99   159.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   3.99   179.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   3.99   179.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   3.99   179.55
13     Sunday       Latte          35   5.99   209.65

In [ ]:
pivot = coffee.pivot(columns='Coffee Type',index='Day',values='revenue')
pivot

Coffee Type  Espresso   Latte
Day
Friday         179.55  209.65
Monday          99.75   89.85
Saturday       179.55  209.65
Sunday         179.55  209.65
Thursday       159.60  179.70
Tuesday        119.70  119.80
Wednesday      139.65  149.75

In [ ]:
pivot.loc['Monday','Latte']

np.float64(89.85000000000001)

In [ ]:
pivot.sum()

Coffee Type
Espresso    1057.35
Latte       1168.05
dtype: float64

In [ ]:
pivot.sum(axis=1)

Day
Friday       389.2
Monday       189.6
Saturday     389.2
Sunday       389.2
Thursday     339.3
Tuesday      239.5
Wednesday    289.4
dtype: float64

In [ ]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [ ]:
bios['born_date'] = pd.to_datetime(bios['born_date'])
bios.groupby(bios['born_date'].dt.year)['name'].count().reset_index().sort_values('name',ascending=False)

     born_date  name
139     1972.0  2231
152     1985.0  2227
140     1973.0  2216
138     1971.0  2205
137     1970.0  2174
..         ...   ...
5       1838.0     1
4       1837.0     1
3       1836.0     1
2       1833.0     1
176     2009.0     1

[177 rows x 2 columns]

In [ ]:
bios[bios['born_date'].dt.year == 1899]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
119,120,Patrick Wheatley,1899-01-20,Vryheid,KwaZulu-Natal,RSA,Great Britain,NaN,NaN,1967-11-05
281,282,S. M. Hadi,1899-08-12,Hyderabad,Andhra Pradesh,IND,India,NaN,NaN,1971-07-14
620,623,Manton Bayley,1899-11-15,Dubbo,New South Wales,AUS,Australia,185.0,NaN,1981-10-17
675,678,Marie Janssen,1899-01-01,NaN,NaN,NaN,Belgium,NaN,NaN,NaN
856,860,Takeichi Harada,1899-05-16,Osaka,Osaka,JPN,Japan,NaN,NaN,1978-06-12
...,...,...,...,...,...,...,...,...,...,...
98239,99033,Huck Woodman,1899-03-11,Winnipeg,Manitoba,CAN,Canada,179.0,75.0,1963-03-17
98399,99195,Hans Zeier,1899-04-24,Luzern (Lucerne),Luzern,SUI,Switzerland,NaN,NaN,1989-08-11
99992,100816,Gyula Szepes,1899-08-18,Spišská Nová Ves,Košice,SVK,Hungary,NaN,NaN,1985-03-02
101667,102588,Wolfgang Kittel,1899-11-11,Charlottenburg,Berlin,GER,Germany,NaN,NaN,1967-02-27
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18

In [ ]:
bios['month_born'] = bios['born_date'].dt.month
bios['year_born'] = bios['born_date'].dt.year
bios.groupby([bios['year_born'],bios['month_born']])['name'].count().reset_index().sort_values('name',ascending=False)

      year_born  month_born  name
1437     1970.0         1.0   239
1461     1972.0         1.0   229
1629     1986.0         1.0   227
1497     1975.0         1.0   227
1617     1985.0         1.0   225
...         ...         ...   ...
95       1857.0         5.0     1
96       1857.0         7.0     1
97       1857.0         8.0     1
98       1857.0         9.0     1
1884     2009.0         1.0     1

[1885 rows x 3 columns]

In [ ]:
coffee['yesterday_revenue'] = coffee['revenue'].shift(2)

In [ ]:
coffee['pct_change'] = coffee['revenue']/coffee['yesterday_revenue'] * 100

In [ ]:
coffee

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change
0,Monday,Espresso,25,3.99,99.75,NaN,NaN
1,Monday,Latte,15,5.99,89.85,NaN,NaN
2,Tuesday,Espresso,30,3.99,119.70,99.75,120.000000
3,Tuesday,Latte,20,5.99,119.80,89.85,133.333333
4,Wednesday,Espresso,35,3.99,139.65,119.70,116.666667
5,Wednesday,Latte,25,5.99,149.75,119.80,125.000000
6,Thursday,Espresso,40,3.99,159.60,139.65,114.285714
7,Thursday,Latte,30,5.99,179.70,149.75,120.000000
8,Friday,Espresso,45,3.99,179.55,159.60,112.500000
9,Friday,Latte,35,5.99,209.65,179.70,116.666667
10,Saturday,Espresso,45,3.99,179.55,179.55,100.000000
11,Saturday,Latte,35,5.99,209.65,209.65,100.000000
12,Sunday,Espresso,45,3.99,179.55,179.55,100.000000
13,Sunday,Latte,35,5.99,209.65,209.65,100.000000

In [ ]:
bios['height_rank'] = bios['height_cm'].rank(ascending=False)

In [ ]:
bios.sort_values(['height_rank']).sample(10)[['name','height_rank']]

                       name  height_rank
38048     Franco De Pedrina      24214.0
34058       Rogério Sampaio      46966.0
31754          Tina Bøttzau      62600.5
44661   Christine Barnetson          NaN
48151      Franco Del Campo      27597.5
34701        Josephus Serré          NaN
87960       Vladimir Krutov      58380.5
39572        Gösta Eriksson          NaN
130691   Miguel Ángel López      11668.0
96623           Walter Sehr          NaN

In [ ]:
coffee.head()

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change
0,Monday,Espresso,25,3.99,99.75,NaN,NaN
1,Monday,Latte,15,5.99,89.85,NaN,NaN
2,Tuesday,Espresso,30,3.99,119.70,99.75,120.000000
3,Tuesday,Latte,20,5.99,119.80,89.85,133.333333
4,Wednesday,Espresso,35,3.99,139.65,119.70,116.666667

In [ ]:
coffee.select_dtypes('float').cumsum()

In [ ]:
coffee['cum_revenue'] = coffee['revenue'].cumsum()

In [84]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [85]:
latte = coffee[coffee['Coffee Type']=='Lattee'].copy()
latte['3day_revenue'] = latte['Units Sold'].rolling(3).sum()

In [86]:
latte

Empty DataFrame
Columns: [Day, Coffee Type, Units Sold, 3day_revenue]
Index: []

In [87]:
pd.__version__

'3.0.3'